<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net9.0</TargetFramework>
    <RuntimeIdentifier>win-arm64</RuntimeIdentifier>
    <PlatformTarget>ARM64</PlatformTarget>
    <UseAppHost>true</UseAppHost>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Ensemble.E0.Core\Ensemble.E0.Core.csproj" />
  </ItemGroup>
</Project>
