<Project Sdk="MSTest.Sdk/4.1.0">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../src/Kymaean.Application/Kymaean.Application.csproj" />
    <ProjectReference Include="../../src/Kymaean.Infrastructure.Persistence/Kymaean.Infrastructure.Persistence.csproj" />
    <ProjectReference Include="../../src/Kymaean.Windows/Presentation/Kymaean.Presentation.csproj" />
  </ItemGroup>
</Project>
