#!/usr/bin/env python3
"""Index documented hashes and lexical MSTest equality assertions; no test execution."""

import argparse
import collections
import pathlib
import re
import subprocess
import sys

ROOT = pathlib.Path(__file__).resolve().parents[1]
OUTPUT = 'docs/evidence/ORACLE_INDEX.md'
HASH = re.compile(r'(?<![0-9a-fA-F])[0-9a-fA-F]{64}(?![0-9a-fA-F])')
# Keep strings intact and discard comments before examining assertion operands.
TOKEN = re.compile(
    r'//[^\n]*|/\*.*?\*/|@"(?:""|[^"])*"|"(?:\\.|[^"\\])*"'
    r"|'(?:\\.|[^'\\])*'|[A-Za-z_][A-Za-z_0-9]*|[^\s]", re.S)


def git(*args):
    return subprocess.check_output(['git', *args], cwd=ROOT)


def hashes(text):
    return {match.group().lower() for match in HASH.finditer(text)}


def asserted_hashes(text):
    """Recognize literal/const-string operands of MSTest AreEqual calls.

    This deliberately is a lexical inventory, not a C# compiler or a claim that
    a test executes. Other assertion styles require a scanner extension.
    """
    tokens = [m.group() for m in TOKEN.finditer(text)
              if not m.group().startswith(('//', '/*'))]
    constants = {}
    for i in range(len(tokens) - 4):
        if tokens[i:i + 2] == ['const', 'string'] and tokens[i + 3] == '=':
            end = i + 4
            while end < len(tokens) and tokens[end] != ';':
                end += 1
            constants[tokens[i + 2]] = tokens[i + 4:end]

    def resolve(operands, seen=frozenset()):
        found = set()
        for token in operands:
            if token.startswith(('"', '@"')):
                found.update(hashes(token))
            elif token in constants and token not in seen:
                found.update(resolve(constants[token], seen | {token}))
        return found

    found = set()
    for i in range(len(tokens) - 4):
        if (tokens[i] not in ('Assert', 'CollectionAssert')
                or tokens[i + 1:i + 4] != ['.', 'AreEqual', '(']):
            continue
        depth = 0
        argument = []
        arguments = []
        for token in tokens[i + 4:]:
            if token == ')' and depth == 0:
                arguments.append(argument)
                break
            if token == ',' and depth == 0:
                arguments.append(argument)
                argument = []
                continue
            if token in ('(', '[', '{'):
                depth += 1
            elif token in (')', ']', '}'):
                depth -= 1
            argument.append(token)
        # Message arguments are not assertions of an oracle value.
        for operand in arguments[:2]:
            found.update(resolve(operand))
    return found


def scan():
    documents = collections.defaultdict(set)
    assertions = collections.defaultdict(set)
    paths = git('ls-files', '-z', '--cached', '--others', '--exclude-standard',
                '--', 'docs/', 'tests/').decode().split('\0')
    for name in sorted(set(paths) - {'', OUTPUT}):
        path = ROOT / name
        if not path.is_file() or {'bin', 'obj'} & set(path.parts):
            continue
        try:
            text = path.read_text(encoding='utf-8-sig')
        except UnicodeDecodeError:
            continue
        if '\0' in text:
            continue
        if name.startswith('docs/'):
            for value in hashes(text):
                documents[value].add(name)
        elif path.suffix == '.cs':
            for value in asserted_hashes(text):
                assertions[value].add(name)
    return {value: (documents[value], assertions[value]) for value in documents}


def render(rows):
    lines = ['# Oracle index', '',
             'Generated by `python tools/oracle-index.py`; do not edit by hand.',
             'ASSERTED denotes a scanned equality assertion, not execution or validation authority.',
             '', '| hash (first 16 chars) | full hash | documents containing it | test files asserting it | status |',
             '| --- | --- | --- | --- | --- |']
    for value, (documents, tests) in sorted(rows.items()):
        cells = [' <br> '.join(f'`{p}`' for p in sorted(paths)) or '-'
                 for paths in (documents, tests)]
        status = 'ASSERTED' if tests else 'DOCUMENT-ONLY'
        lines.append(f'| `{value[:16]}` | `{value}` | {cells[0]} | {cells[1]} | {status} |')
    return '\n'.join(lines) + '\n'


def parse_index(text):
    rows = {}
    for line in text.splitlines():
        if not line.startswith('| `'):
            continue
        cells = [cell.strip() for cell in line.strip('|').split('|')]
        if len(cells) != 5 or not HASH.fullmatch(cells[1].strip('`')):
            raise ValueError(f'Malformed index row: {line}')
        value = cells[1].strip('`').lower()
        documents, tests = [set(re.findall(r'`([^`]+)`', cell)) for cell in cells[2:4]]
        if value in rows or cells[4] != ('ASSERTED' if tests else 'DOCUMENT-ONLY'):
            raise ValueError(f'Inconsistent index row: {value}')
        rows[value] = (documents, tests)
    return rows


def committed_index(ref, required=False):
    # Resolve the revision separately: a missing revision must not bypass checks.
    commit = git('rev-parse', '--verify', f'{ref}^{{commit}}').decode().strip()
    exists = git('ls-tree', '--name-only', commit, '--', OUTPUT).decode().strip()
    if not exists:
        if required:
            raise ValueError(f'{OUTPUT} is not committed at {ref}')
        return None
    return git('show', f'{commit}:{OUTPUT}').decode('utf-8-sig').replace('\r\n', '\n')


def differences(old, new, regressions_only=False):
    failures = []
    for value in sorted(old.keys() | new.keys()):
        before = old.get(value, (set(), set()))
        after = new.get(value, (set(), set()))
        regressed = bool(before[1]) and not after[1]
        if before == after or (regressions_only and not regressed):
            continue
        files = (before[0] ^ after[0]) | (before[1] ^ after[1])
        reason = 'ASSERTED lost its assertion coverage' if regressed else 'index drift'
        for path in sorted(files):
            failures.append(f'{reason}: hash {value}; changed file {path}')
    return failures


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true', help='regenerate and compare with HEAD')
    parser.add_argument('--baseline', help='also reject assertion loss against this prior Git revision')
    args = parser.parse_args()
    rows = scan()
    generated = render(rows)
    failures = []
    if args.check:
        committed = committed_index('HEAD', required=True)
        failures.extend(differences(parse_index(committed), rows))
        if committed != generated and not failures:
            failures.append(f'Index formatting drift: changed file {OUTPUT}')
    if args.baseline:
        previous = committed_index(args.baseline)
        if previous is not None:
            failures.extend(differences(parse_index(previous), rows, regressions_only=True))
    destination = ROOT / OUTPUT
    destination.parent.mkdir(parents=True, exist_ok=True)
    destination.write_text(generated, encoding='utf-8', newline='\n')
    asserted = sum(bool(tests) for _, tests in rows.values())
    print(f'{asserted} ASSERTED, {len(rows) - asserted} DOCUMENT-ONLY')
    for failure in sorted(set(failures)):
        print(f'ERROR: {failure}', file=sys.stderr)
    return 1 if failures else 0


if __name__ == '__main__':
    try:
        sys.exit(main())
    except (OSError, ValueError, subprocess.CalledProcessError) as error:
        print(f'ERROR: {error}', file=sys.stderr)
        sys.exit(1)
